beetl:
  templatesPath: /templates
  enabled: true
beetl-beetlsql:
  dev: true
server:
  port: 8097
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/iotlock?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: iotlock
    password: R5K5r9727@t

